id: c355954744d04f768b5993b9bc0c9679
initial_creation_type: ocr
source_metadata:
  volumes:
    44d64bd8d44f4649afd2eecbf03d3a5b:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་མའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
